definitions:
  services:
    docker:
      memory: 4096

pipelines:
  branches:
    all-in-one:
      - step:
          name: build
          size: 2x
          services:
            - docker
          script:
            - ssh -tt huoju@103.61.37.242 "cd /data/deploy/build-server/build_shortcuts && git pull && ./10_build_all_in_one_light_timeline.sh"
            - ssh -tt Junhong@34.131.81.93 "cd ~/deploy/feedbaseone && git pull && ./redeploy_all_in_one_light_timeline.sh"
